#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory

source /etc/device_config

detect_ad936x_defaults () {
	MODEL_TEXT=`cat /sys/firmware/devicetree/base/model 2> /dev/null`

	AD936X_DEFAULT_ATTR_VAL=ad9364
	AD936X_DEFAULT_MODE=1r1t

	if echo "$MODEL_TEXT" | grep -q "Rev.C"
	then
		AD936X_DEFAULT_ATTR_VAL=ad9361
		AD936X_DEFAULT_MODE=2r2t
	fi
}

create_system_files () {

	UDHCPD_CONF=/etc/udhcpd.conf
	CONF=/opt/config.txt
	IFAC=/etc/network/interfaces

	HOSTNAME=`fw_printenv -n hostname 2> /dev/null || echo pluto`
	echo $HOSTNAME > /etc/hostname

	IPADDR=`fw_printenv -n ipaddr 2> /dev/null || echo 192.168.2.1`
	IPADDR_HOST=`fw_printenv -n ipaddr_host 2> /dev/null || echo 192.168.2.10`
	NETMASK=`fw_printenv -n netmask 2> /dev/null || echo 255.255.255.0`

	ETH_IPADDR=`fw_printenv -n ipaddr_eth 2> /dev/null`
	ETH_NETMASK=`fw_printenv -n netmask_eth 2> /dev/null || echo 255.255.255.0`
	ETH_FALLBACK_IP=`fw_printenv -n ipaddr_eth_fallback 2> /dev/null || echo 192.168.3.1`
	ETH_FALLBACK_START=`fw_printenv -n ipaddr_eth_fallback_start 2> /dev/null || echo 192.168.3.10`
	ETH_FALLBACK_END=`fw_printenv -n ipaddr_eth_fallback_end 2> /dev/null || echo 192.168.3.99`
	ETH_MACADDR=`fw_printenv -n macaddr_eth 2> /dev/null || fw_printenv -n ethaddr 2> /dev/null || echo 00:0a:35:00:01:22`

	WLAN_SSID=`fw_printenv -n ssid_wlan 2> /dev/null`
	WLAN_PWD=`fw_printenv -n pwd_wlan 2> /dev/null`
	WLAN_IPADDR=`fw_printenv -n ipaddr_wlan 2> /dev/null`

	XO_CORRECTION=`fw_printenv -n xo_correction 2> /dev/null`
	UDC_HANDLE_SUSPEND=`fw_printenv -n udc_handle_suspend 2> /dev/null || echo 0`
	USB_ETH_MODE=`fw_printenv -n usb_ethernet_mode 2> /dev/null || echo rndis`
	detect_ad936x_defaults
	AD936X_ATTR_NAME=`fw_printenv -n attr_name 2> /dev/null || echo compatible`
	AD936X_ATTR_VAL=`fw_printenv -n attr_val 2> /dev/null || echo $AD936X_DEFAULT_ATTR_VAL`
	AD936X_COMPATIBLE=`fw_printenv -n compatible 2> /dev/null || echo $AD936X_ATTR_VAL`
	AD936X_MODE=`fw_printenv -n mode 2> /dev/null || echo $AD936X_DEFAULT_MODE`
	AD936X_FORCE_2R2T=`fw_printenv -n force_2r2t 2> /dev/null || echo 0`

	if [ "$AD936X_FORCE_2R2T" == "1" ]
	then
		AD936X_ATTR_NAME=compatible
		AD936X_ATTR_VAL=ad9361
		AD936X_COMPATIBLE=ad9361
		AD936X_MODE=2r2t
	fi

	### /etc/udhcpd.conf ###
	echo "start $IPADDR_HOST" > $UDHCPD_CONF
	echo "end $IPADDR_HOST" >> $UDHCPD_CONF
	echo "interface usb0" >> $UDHCPD_CONF
	echo "option subnet $NETMASK" >> $UDHCPD_CONF

	### /etc/network/interfaces ###
	echo -e "auto lo\n""iface lo inet loopback\n" > $IFAC
	echo -e "auto usb0\n""iface usb0 inet static" >> $IFAC
	echo -e "\taddress $IPADDR\n""\tnetmask $NETMASK\n" >> $IFAC
	echo -e "auto usb1\n""iface usb1 inet dhcp\n" >> $IFAC

	echo -e "iface eth0 inet manual\n" >> $IFAC

	### /etc/wpa.conf ###
	if [ -n "$WLAN_SSID" ]
	then
		if [ -n "$WLAN_PWD" ]
		then
			wpa_passphrase "$WLAN_SSID" "$WLAN_PWD" > /etc/wpa.conf
		else
			echo "network={" > /etc/wpa.conf
			echo "    ssid=\"$WLAN_SSID\"" >> /etc/wpa.conf
			echo "    key_mgmt=NONE" >> /etc/wpa.conf
			echo "}" >> /etc/wpa.conf
		fi

		echo -e "auto wlan0" >> $IFAC

		if [ -n "$WLAN_IPADDR" ]
		then
			echo -e "iface wlan0 inet static" >> $IFAC
			echo -e "\taddress $WLAN_IPADDR\n""\tnetmask 255.255.255.0" >> $IFAC
		else
			echo -e "iface wlan0 inet dhcp" >> $IFAC
		fi
		echo -e "\twpa-conf /etc/wpa.conf\n" >> $IFAC
	fi

	### /opt/config.txt ###
	echo "# $(cat /sys/firmware/devicetree/base/model | tr / -)"$'\r' > $CONF
	echo "# Device Configuration File"$'\r' >> $CONF
	echo "#   1. Open with an Editor"$'\r' >> $CONF
	echo "#   2. Edit this file"$'\r' >> $CONF
	echo "#   3. Save this file on the device USB drive"$'\r' >> $CONF
	echo "#   4. Eject the device USB Drive"$'\r' >> $CONF
	echo "# Doc: https://wiki.analog.com/university/tools/pluto/users/customizing"$'\r' >> $CONF
	echo ""$'\r'>> $CONF
	echo "[NETWORK]"$'\r' >> $CONF
	echo "hostname = $HOSTNAME"$'\r' >> $CONF
	echo "ipaddr = $IPADDR"$'\r' >> $CONF
	echo "ipaddr_host = $IPADDR_HOST"$'\r' >> $CONF
	echo "netmask = $NETMASK"$'\r' >> $CONF
	echo ""$'\r'>> $CONF
	echo "[WLAN]"$'\r' >> $CONF
	echo "ssid_wlan = $WLAN_SSID"$'\r' >> $CONF
	echo "pwd_wlan = $WLAN_PWD"$'\r' >> $CONF
	echo "ipaddr_wlan = $WLAN_IPADDR"$'\r' >> $CONF
	echo ""$'\r'>> $CONF
	echo "[USB_ETHERNET]"$'\r' >> $CONF
	echo "ipaddr_eth = $ETH_IPADDR"$'\r' >> $CONF
	echo "netmask_eth = $ETH_NETMASK"$'\r' >> $CONF
	echo "ipaddr_eth_fallback = $ETH_FALLBACK_IP"$'\r' >> $CONF
	echo "ipaddr_eth_fallback_start = $ETH_FALLBACK_START"$'\r' >> $CONF
	echo "ipaddr_eth_fallback_end = $ETH_FALLBACK_END"$'\r' >> $CONF
	echo "macaddr_eth = $ETH_MACADDR"$'\r' >> $CONF
	echo ""$'\r'>> $CONF
	echo "[AD936X]"$'\r' >> $CONF
	echo "# Extended tuning range: ad9364 uses 1r1t, ad9361 uses 2r2t"$'\r' >> $CONF
	echo "# Pluto Plus 2R2T test override: set force_2r2t to 1 only on boards with TX2/RX2 hardware"$'\r' >> $CONF
	echo "force_2r2t = $AD936X_FORCE_2R2T"$'\r' >> $CONF
	echo "attr_name = $AD936X_ATTR_NAME"$'\r' >> $CONF
	echo "attr_val = $AD936X_ATTR_VAL"$'\r' >> $CONF
	echo "compatible = $AD936X_COMPATIBLE"$'\r' >> $CONF
	echo "mode = $AD936X_MODE"$'\r' >> $CONF
	echo ""$'\r'>> $CONF
	echo "[SYSTEM]"$'\r' >> $CONF
	echo "xo_correction = $XO_CORRECTION"$'\r' >> $CONF
	echo "udc_handle_suspend = $UDC_HANDLE_SUSPEND"$'\r' >> $CONF
	echo "# USB Communication Device Class Compatibility Mode [rndis|ncm|ecm]"$'\r' >> $CONF
	echo "usb_ethernet_mode = $USB_ETH_MODE"$'\r' >> $CONF
	echo ""$'\r'>> $CONF
	echo "[ACTIONS]"$'\r' >> $CONF
	echo "diagnostic_report = 0"$'\r' >> $CONF
	echo "dfu = 0"$'\r' >> $CONF
	echo "reset = 0"$'\r' >> $CONF
	echo "calibrate = 0"$'\r' >> $CONF
	echo "device_persistent_keys = 0"$'\r' >> $CONF
	echo ""$'\r'>> $CONF

	### /www/index.html ###

	sed -i -e "s/#IP#/$IPADDR/g" -e "s/#HOSTIP#/$IPADDR_HOST/g" -e "s/#NETMASK#/$NETMASK/g" -e "s/#HOSTNAME#/$HOSTNAME/g" -e "s/#SSID_WLAN#/$WLAN_SSID/g" -e "s/#IPADDR_WLAN#/$WLAN_IPADDR/g" -e "s/#IPADDR_ETH#/$ETH_IPADDR/g" -e "s/#NETMASK_ETH#/$ETH_NETMASK/g" /www/index.html

	}

set_eth_macaddr () {
	case "$ETH_MACADDR" in
		[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F])
			/sbin/ifconfig eth0 down 2>/dev/null
			/sbin/ifconfig eth0 hw ether "$ETH_MACADDR"
			;;
		*)
			logger -t S40network "Ignoring invalid eth0 MAC address: $ETH_MACADDR"
			return 1
			;;
	esac
}

mkdir -p /run/network

case "$1" in
  start)
	create_system_files
	set_eth_macaddr
	printf "Starting network: "
	/bin/hostname -F /etc/hostname
	/sbin/ifup -a 2>&1 | logger
	ETH_IPADDR="$ETH_IPADDR" \
	ETH_FALLBACK_IP="$ETH_FALLBACK_IP" \
	ETH_FALLBACK_NETMASK="$ETH_NETMASK" \
	ETH_FALLBACK_START="$ETH_FALLBACK_START" \
	ETH_FALLBACK_END="$ETH_FALLBACK_END" \
	/usr/sbin/pluto-eth-fallback eth0 >/dev/null 2>&1 &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping network: "
	/sbin/ifdown -a
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
