#!/bin/sh
# Server-side demuxing by default

source /etc/device_config

case "$1" in
	start)
		echo -n "Starting dhcpd Daemon: "
		start-stop-daemon -S -q -p /var/run/udhcpd.pid -x /usr/sbin/udhcpd -- $UDHCPD_CONF
		if [ -f /etc/udhcpd-eth0.conf ]; then
			start-stop-daemon -S -q -p /var/run/udhcpd-eth0.pid -x /usr/sbin/udhcpd -- /etc/udhcpd-eth0.conf
		fi
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;

	stop)
		echo -n "Stopping dhcpd Daemon: "
		start-stop-daemon -K -q -p /var/run/udhcpd.pid 2>/dev/null
		start-stop-daemon -K -q -p /var/run/udhcpd-eth0.pid 2>/dev/null
		start-stop-daemon -K -q -p /var/run/udhcpc-eth0.pid 2>/dev/null
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
