#!/bin/sh
#
# Script to check for and run user-supplied /mnt/jffs2/autorun.sh
#

case "$1" in
  start)
	(
		if ! /usr/sbin/pluto-sdcard-prepare --all; then
			logger -t S98autostart "SD card preparation failed; not running autorun.sh"
			exit 1
		fi

		if test -x /usr/sbin/pluto-web-apply-settings; then
			/usr/sbin/pluto-web-apply-settings
		fi

		if test -f /mnt/jffs2/autorun.sh; then
			. /mnt/jffs2/autorun.sh
		fi
	) &
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
